# workflowにつける任意の名前
name: hoge

on: [push]

# jobにつける任意の名前
jobs:
  run-shell-cmd:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world"
      - name: multiline script
        run: |
          node -v
          npm -v
